/* istanbul ignore file */
/**
 * This file is automatically created by Recurly's OpenAPI generation process
 * and thus any edits you make by hand will be lost. If you wish to make a
 * change to this file, please create a Github issue explaining the changes you
 * need and we will usher them to the appropriate places.
 */
'use strict'

const Resource = require('../Resource')

/**
 * GiftCard
 * @typedef {Object} GiftCard
 * @prop {number} balance - The remaining credit on the recipient account associated with this gift card. Only has a value once the gift card has been redeemed. Can be used to create gift card balance displays for your customers.
 * @prop {Date} canceledAt - When the gift card was canceled.
 * @prop {Date} createdAt - Created at
 * @prop {string} currency - 3-letter ISO 4217 currency code.
 * @prop {Date} deliveredAt - When the gift card was sent to the recipient by Recurly via email, if method was email and the "Gift Card Delivery" email template was enabled. This will be empty for post delivery or email delivery where the email template was disabled.
 * @prop {GiftCardDelivery} delivery - The delivery details for the gift card.
 * @prop {string} gifterAccountId - The ID of the account that purchased the gift card.
 * @prop {string} id - Gift card ID
 * @prop {string} object - Object type
 * @prop {string} productCode - The product code or SKU of the gift card product.
 * @prop {string} purchaseInvoiceId - The ID of the invoice for the gift card purchase made by the gifter.
 * @prop {string} recipientAccountId - The ID of the account that redeemed the gift card redemption code.  Does not have a value until gift card is redeemed.
 * @prop {Date} redeemedAt - When the gift card was redeemed by the recipient.
 * @prop {string} redemptionCode - The unique redemption code for the gift card, generated by Recurly. Will be 16 characters, alphanumeric, displayed uppercase, but accepted in any case at redemption. Used by the recipient account to create a credit in the amount of the `unit_amount` on their account.
 * @prop {string} redemptionInvoiceId - The ID of the invoice for the gift card redemption made by the recipient.  Does not have a value until gift card is redeemed.
 * @prop {number} unitAmount - The amount of the gift card, which is the amount of the charge to the gifter account and the amount of credit that is applied to the recipient account upon successful redemption.
 * @prop {Date} updatedAt - Last updated at
 */
class GiftCard extends Resource {
  static getSchema () {
    return {
      balance: Number,
      canceledAt: Date,
      createdAt: Date,
      currency: String,
      deliveredAt: Date,
      delivery: 'GiftCardDelivery',
      gifterAccountId: String,
      id: String,
      object: String,
      productCode: String,
      purchaseInvoiceId: String,
      recipientAccountId: String,
      redeemedAt: Date,
      redemptionCode: String,
      redemptionInvoiceId: String,
      unitAmount: Number,
      updatedAt: Date
    }
  }
}

module.exports = GiftCard
