/* istanbul ignore file */
/**
 * This file is automatically created by Recurly's OpenAPI generation process
 * and thus any edits you make by hand will be lost. If you wish to make a
 * change to this file, please create a Github issue explaining the changes you
 * need and we will usher them to the appropriate places.
 */
'use strict'

const Resource = require('../Resource')

/**
 * SubscriptionChangeBillingInfo
 * @typedef {Object} SubscriptionChangeBillingInfo
 * @prop {string} threeDSecureActionResultTokenId - A token generated by Recurly.js after completing a 3-D Secure device fingerprinting or authentication challenge.
 */
class SubscriptionChangeBillingInfo extends Resource {
  static getSchema () {
    return {
      threeDSecureActionResultTokenId: String
    }
  }
}

module.exports = SubscriptionChangeBillingInfo
