#!/usr/bin/env bash
set -e

npm install

# Need to clean docs first
rm -rf docs/
./node_modules/.bin/documentation build lib/recurly/**  --format html --output docs --theme node_modules/documentation-theme-light --config documentation.yml

# append custom css to doc build's css
cat doc/custom.css >> docs/assets/style.css
cat doc/custom.css >> docs/assets/styles.min.css
