#!/usr/bin/env bash
set -e

function check_for_command {
  if ! hash eval "$1" 2>/dev/null; then
    echo "✖ Could not find '$1'" 
    exit 1
  fi
  echo "✓ Found $1"
}

check_for_command "npm"
check_for_command "node"

NODE_VERSION=$(node --version)
NODE_MAJOR=$(node --version | cut -d' ' -f2 | cut -d'.' -f1 | sed 's/v//')
NODE_MINOR=$(node --version | cut -d' ' -f2 | cut -d'.' -f2)

function unsupported_version {
  echo "✖ Unsupported node version is ${NODE_VERSION}"
  exit 1
}

if [ "$NODE_MAJOR" -lt "7" ]; then
  unsupported_version
else
  echo "✓ Version ${NODE_VERSION} is compatible"
fi
