#!/usr/bin/env bash
set -e

if ! hash brew 2>/dev/null; then
  echo "✖ Homebrew not found. Please install: https://brew.sh/"
  exit 1
else
  echo "✓ Found homebrew"
fi

if ! hash node 2>/dev/null; then
  read -p "✖ 'node' not found. Would you like to install it? [Y/n] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy\n]$ ]]
  then
    brew install node && true
    echo
  else
    exit 1
  fi
else
  echo "✓ Found node"
fi
