#!/usr/bin/env bash
set -e

# TODO this file could be gone
RELEASED_LOG="/tmp/node-pending-changes.md"
THIS_VERSION=$(./scripts/bump --this-version)

# push the tag
git push origin $THIS_VERSION

# publish to npm
npm publish

# Finally need to update the full changelog
./scripts/changelog
git add CHANGELOG.md
git commit -m "Update Changelog for Release $THIS_VERSION"
git push origin master

# Copy-pasteable messages for announcments
echo "Npm: https://www.npmjs.com/package/recurly/v/$THIS_VERSION"
echo "Release: https://github.com/recurly/recurly-client-node/releases/tag/$THIS_VERSION"
echo "Changelog:"
cat "$RELEASED_LOG"
