#!/usr/bin/env bash
set -e

NODE_FLAGS=""
NODE_MAJOR_VERSION=$(node --version | cut -d '.' -f 1)
if [[ "${NODE_MAJOR_VERSION:1}" -lt 10 ]]; then
  NODE_FLAGS="--harmony_async_iteration"
fi

if [ "$1" = "--watch" ]; then
  node $NODE_FLAGS./node_modules/.bin/_mocha --recursive --watch
else
  node $NODE_FLAGS ./node_modules/.bin/standard "lib/**/*.js" "test/**/*.js" && \
  ./node_modules/.bin/nyc --reporter=html node $NODE_FLAGS ./node_modules/.bin/_mocha --recursive && \
  ./node_modules/.bin/tsc lib/recurly.d.ts
fi
