#!/usr/bin/env bash

if [ "$1" = "--watch" ]; then
  ./node_modules/.bin/mocha --recursive --watch
else
  ./node_modules/.bin/standard && \
  ./node_modules/.bin/nyc --reporter=html ./node_modules/.bin/mocha --recursive
fi
