#!/usr/bin/env bash
set -e

if [ "$1" = "--watch" ]; then
  ./node_modules/.bin/mocha --recursive --watch
else
  ./node_modules/.bin/standard "lib/**/*.js" "test/**/*.js" && \
  ./node_modules/.bin/nyc --reporter=html ./node_modules/.bin/mocha --recursive && \
  ./node_modules/.bin/tsc lib/recurly.d.ts
fi
