on:
  release:
    types:
      - released
name: Documentation
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build Library and Docs
      run: ./scripts/build

    - name: Deploy
      if: success()
      # use the specific sha of 3rd party libraries for security reasons https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
      uses: crazy-max/ghaction-github-pages@071043bf3d88171bec60f5089a7cbfd084d53c42
      with:
        target_branch: gh-pages
        build_dir: ./docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

