name: Security check - ESLint

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - staging
      - main
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stefanoeb/eslint-action@1.0.2
        continue-on-error: true